name: Upstream Sync

on:
    schedule:
        - cron: "0 0 * * 0"
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout target repo
              uses: actions/checkout@v4
              with:
                ref:  develop
                persist-credentials: false

            - name: Sync upstream changes
              id: sync
              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
              with:
                target_sync_branch: develop
                target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                upstream_sync_branch: main
                upstream_sync_repo: Chia-Network/bls-signatures

            - name: Show value of 'has_new_commits'
              run: echo ${{ steps.sync.outputs.has_new_commits }}

            - name: Create Pull Request
              if: steps.sync.outputs.has_new_commits == 'true'
              id: cpr
              uses: peter-evans/create-pull-request@v4
              with:
                token: ${{ secrets.GH_TOKEN }}
                commit-message: "chore: merge upstream changes"
                committer: GitHub <noreply@github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                branch: chore/sync-upstream
                delete-branch: true
                title: "chore: merge upstream changes"
                draft: false